### ISSUE TITLE
Error in `exclude' regular expression. 

### ISSUE THREAD

**Issue by garylab** [pstauffer/docker-inotify#8]
I meet error:
```
$ docker-compose up inotify
Pulling inotify (pstauffer/inotify:v1.0.1)...
v1.0.1: Pulling from pstauffer/inotify
Creating dnmp_inotify_1 ... done
Attaching to dnmp_inotify_1
inotify_1        \| Error in `exclude' regular expression.
inotify_1        \| inotify settings
inotify_1        \| ================
inotify_1        \|
inotify_1        \|   Container:        php72
inotify_1        \|   Volumes:          /data
inotify_1        \|   Curl_Options:
inotify_1        \|   Signal:           SIGHUP
inotify_1        \|   Inotify_Events:   create,delete,modify,move
inotify_1        \|   Inotify_Options:  --monitor --exclude=*.sw[px]
inotify_1        \|
inotify_1        \| [Starting inotifywait...]
dnmp_inotify_1 exited with code 0
```
My docker-compose.yml file is:
```
  inotify:
    image: pstauffer/inotify:v1.0.1
    tty: "true"
    volumes:
      - ${SOURCE_DIR}/theme/themefile/:/data:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - CONTAINER=php72
      - VOLUMES=/data
```
